spring:
  datasource:
    url: jdbc:postgresql://localhost/angular
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED

allowed:
  origins: https://localhost:4200

okta:
  oauth2:
    client-id: 0oa8di4rh6jqTQ6tP5d7
    issuer: https://dev-01620059.okta.com/oauth2/default

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: shop
    key-store: classpath:shop-keystore.p12
    key-store-password: secret
    key-store-type: PKCS12

stripe:
  key:
    secret: sk_test_51Mg8tNB0o4mb8zXyUCdUarEZiAbcrsOqVwTErCJD1K3BZg5SnfykFkQhKVlSXAUJ4JbG6Y8H3k5d1NmCVGM6biDR00zvhnuf2b